version: "3"
services:
  hub4tests:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/run.sh:/data/run.sh

      # The slightly modified file that hides non enabled idps
      - ./development/selectidp-links.php:/data/vendor/simplesamlphp/simplesamlphp/templates/selectidp-links.php

      # Utilize custom certs
      - ./development/hub4tests/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/hub4tests/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/hub4tests/metadata/idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/idp-remote.php
      - ./development/hub4tests/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/hub4tests/metadata/saml20-sp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-hosted.php
      - ./development/hub4tests/metadata/sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/sp-remote.php

      # Override the initial SSOService.php file, to ensure this module is used
      - ./sspoverrides/www_saml2_idp/SSOService.php:/data/vendor/simplesamlphp/simplesamlphp/www/saml2/idp/SSOService.php

      # Utilize this module's files
      - ./lib:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/lib
      - ./www:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/www
      - ./tests:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/tests

      # Configure the debugger
      - ./development/hub4tests/run-debug.sh:/data/run-debug.sh
    command: /data/run-debug.sh

    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=1234qwer
      - SECRET_SALT=h57fjemb&dn^nsJFGNjweJ
      - SECURE_COOKIE=false
      - ADMIN_PROTECT_INDEX_PAGE=false
      - SHOW_SAML_ERRORS=true
      - HUB_MODE=true
      - IDP_NAME=Hub4Tests


  idp1:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/run.sh:/data/run.sh

      # Revert to standard SSOService.php instead of using sildisco'saml20-idp-hosted
      - ./development/SSOService.php:/data/vendor/simplesamlphp/simplesamlphp/www/saml2/idp/SSOService.php

      # Utilize custom certs
      - ./development/idp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    command: /data/run.sh

    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=a
      - SECRET_SALT=h57fjemb&dn^nsJFGNjweJ
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - IDP_NAME=IdP1

  idp2:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/run.sh:/data/run.sh

      # Revert to standard SSOService.php instead of using sildisco'saml20-idp-hosted
      - ./development/SSOService.php:/data/vendor/simplesamlphp/simplesamlphp/www/saml2/idp/SSOService.php

      # Utilize custom certs
      - ./development/idp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp2-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp2-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    command: /data/run.sh

    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=b
      - SECRET_SALT=h57fjemb&dn^nsJFGNjweJ
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - IDP_NAME=IdP2

  idp3:
    image: silintl/ssp-base:develop
    volumes:
      # Utilize custom certs
      - ./development/idp3-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp3-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp3-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp3-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp3-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    command: /data/run.sh

    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "c"
      SECRET_SALT: "h57fjem34fh*nsJFGNjweJ"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      IDP_NAME: "IdP3"

  sp1:
    image: silintl/ssp-base:develop
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=sp1
      - SECRET_SALT=h57fjemb&dn^nsJFGNjweJz1
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false


  sp2:
    image: silintl/ssp-base:develop
    volumes:
      # Utilize custom certs
      - ./development/sp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp2-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=sp2
      - SECRET_SALT=h57fjemb&dn^nsJFGNjweJz2
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false


  sp3:
    image: silintl/ssp-base:develop
    volumes:
      # Utilize custom certs
      - ./development/sp3-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp3-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp3-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp3-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=sp3
      - SECRET_SALT=h57fjemb&dn^nsJFGNjweJz3
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false


  browsertest:
    build: ./development/browser_test/
    volumes:
      - ./features/:/data/features/
    depends_on:
       - hub4tests
       - sp1
       - sp2
       - sp3
       - idp1
       - idp2
       - idp3
       - chrome
    command: ["whenavail", "hub4tests", "80", "60", "vendor/bin/behat"]

  chrome:
    image: justinribeiro/chrome-headless:stable
    cap_add:
      - SYS_ADMIN

  unittest:
    image: silintl/ssp-base:develop
    volumes:

      - ./development/run-tests.sh:/data/run-tests.sh
      - ./development/run-debug.sh:/data/run-debug.sh

      # Utilize this module's files
      - ./lib:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/lib
      - ./www:/data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/www
      - ./dev-tests:/data/dev-tests

    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=1234qwer
      - SECRET_SALT=h57fjemb&dn^nsJFGNjweJ
      - SECURE_COOKIE=false
      - ADMIN_PROTECT_INDEX_PAGE=false
      - HUB_MODE=true
      - IDP_NAME=UnitTest
